import { test } from "node:test";
import assert from "node:assert/strict";
import { Ledger, normalizeUsage, makeRecord, footer } from "../src/core.mjs";
import { isPeak, deepseekRates, costFor } from "../src/pricing.mjs";
const time = Date.parse("2026-09-10T07:00:00Z");
const usage = (input, cacheRead, output = 10) => ({ input, cacheRead, output, cacheWrite: 0 });
const message = (id, u = usage(10, 90), extra = {}) => ({ role: "assistant", responseId: id, provider: "deepseek", model: "deepseek-flash", timestamp: time, usage: u, stopReason: "stop", ...extra });
const record = (id, session, u, seconds = 1) => makeRecord(message(id, u), session, { startedAt: time, firstTokenAt: time + 100, endedAt: time + 100 + seconds * 1000 });
test("raw DeepSeek hits are a subset of prompt tokens; reasoning is not counted twice", () => {
  assert.deepEqual(normalizeUsage({ prompt_tokens: 100, prompt_cache_hit_tokens: 90, prompt_cache_miss_tokens: 10, completion_tokens: 20, completion_tokens_details: { reasoning_tokens: 15 } }), usage(10, 90, 20));
  assert.equal(normalizeUsage({ prompt_tokens: 5, prompt_cache_hit_tokens: 6, completion_tokens: 1 }), undefined);
  assert.equal(normalizeUsage({ input: 5, output: 1 }), undefined);
  assert.equal(normalizeUsage({ ...usage(5, 0), cacheRead: NaN }), undefined);
});
test("tree cache hit is token-weighted, TPS uses summed request durations, duplicates don't add cost", () => {
  const ledger = new Ledger();
  ledger.apply({ type: "session", id: "parent" });
  ledger.apply({ type: "session", id: "child", parentId: "parent" });
  ledger.apply({ type: "session", id: "grandchild", parentId: "child" });
  const one = record("1", "parent", usage(10, 90, 100), 2);
  ledger.apply(one); ledger.apply(one);
  ledger.apply(record("2", "child", usage(900, 0, 200), 2));
  ledger.apply(record("3", "grandchild", usage(0, 100, 100), 1));
  const summary = ledger.summarize("parent");
  assert.equal(summary.requests, 3);
  assert.equal(summary.cacheHitRate, 190 / 1100);
  assert.equal(summary.tps, 400 / 5);
  assert.equal(ledger.summarize("parent", "parent").requests, 1);
  assert.equal(ledger.summarize("parent", "children").requests, 2);
  assert.equal(ledger.summarize("parent").costUsd, [...ledger.requests.values()].reduce((n, r) => n + r.costUsd, 0));
});
test("DeepSeek peak windows, weekend, alias retirement, stale snapshot and reseller separation", () => {
  assert.equal(isPeak(Date.parse("2026-09-10T01:00:00Z")), true);
  assert.equal(isPeak(Date.parse("2026-09-10T04:00:00Z")), false);
  assert.equal(isPeak(Date.parse("2026-09-10T06:00:00Z")), true);
  assert.equal(isPeak(Date.parse("2026-09-10T10:00:00Z")), false);
  assert.equal(isPeak(Date.parse("2026-09-12T07:00:00Z")), false);
  assert.equal(deepseekRates("deepseek-flash", time).input, 0.3);
  assert.equal(deepseekRates("deepseek-flash", Date.parse("2026-09-12T07:00:00Z")).input, 0.15);
  assert.equal(deepseekRates("deepseek-v4-pro", Date.parse("2026-09-14T03:59:00Z")).input, 1.32);
  assert.equal(deepseekRates("deepseek-v4-pro", Date.parse("2026-09-14T04:00:00Z")).input, 0.15);
  assert.equal(deepseekRates("unknown", time), undefined);
  assert.equal(deepseekRates("deepseek-flash", Date.parse("2026-09-25")), undefined);
  const pricing = costFor(message("x"), usage(1e6, 1e6, 1e6), undefined, time, time);
  assert.equal(pricing.costUsd, 1.506);
  assert.equal(costFor(message("x", { ...usage(1, 0), cost: { total: 0.5 } }, { provider: "openrouter" }), usage(1, 0), undefined, time, time).costUsd, 0.5);
});
test("unknown costs and failed zero-filled usage are explicit, not free", () => {
  const ledger = new Ledger(); ledger.apply({ type: "session", id: "p" });
  ledger.apply(makeRecord(message("error", usage(0, 0, 0), { stopReason: "error" }), "p"));
  const summary = ledger.summarize("p");
  assert.equal(summary.unknownUsage, 1); assert.equal(summary.unpriced, 1);
  assert.equal(summary.cacheHitRate, undefined); assert.match(footer(summary), /partial/);
});
test("child summaries replace incomplete observations, never double count", () => {
  const ledger = new Ledger();
  ledger.apply({ type: "session", id: "p" });
  ledger.apply({ type: "session", id: "c", parentId: "p", agentId: "agent1234" });
  ledger.apply(record("1", "c", usage(10, 10)));
  ledger.apply({ type: "child", id: "agent1234", parentId: "p", usage: { ...usage(20, 20, 20), cost: { total: 0.1 } }, status: "complete" });
  assert.equal(ledger.summarize("p").promptTokens, 40);
  assert.equal(ledger.summarize("p").summaryChildren, 1);
  assert.equal(ledger.summarize("p").tps, undefined, "Whole-child duration is not generation TPS");
  ledger.apply(record("2", "c", usage(10, 10)));
  assert.equal(ledger.summarize("p").summaryChildren, 0);
  assert.equal(ledger.summarize("p").promptTokens, 40);
  ledger.apply({ type: "child", id: "unobserved", parentId: "p", status: "running" });
  assert.equal(ledger.summarize("p").unknownChildren, 1);
});
test("parent-file lineage and delayed in-memory subagent identification resolve", () => {
  const ledger = new Ledger();
  ledger.apply({ type: "session", id: "c", parentFile: "/parent.jsonl" });
  ledger.apply({ type: "session", id: "p", file: "/parent.jsonl" });
  ledger.apply({ type: "session", id: "m", agentShortId: "12345678" });
  ledger.apply({ type: "child", id: "12345678-abc", parentId: "p" });
  assert.deepEqual([...ledger.descendants("p")].sort(), ["c", "m", "p"]);
  ledger.apply({ type: "session", id: "p", parentId: "c" });
  assert.equal(ledger.descendants("p").size, 3, "Cycles cannot hang the meter");
});
