import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Observer } from "../src/observer.mjs";
const usage = { input: 10, cacheRead: 90, cacheWrite: 0, output: 10, cost: { total: 0.01 } };
test("retained history, compaction usage, child transcript import, and restart deduplication", async () => {
  const dir = await mkdtemp(join(tmpdir(), "usage-observer-"));
  const parentFile = join(dir, "parent.jsonl"), childFile = join(dir, "child.jsonl");
  await writeFile(parentFile, JSON.stringify({ type: "session", id: "p" }) + "\n");
  const message = { role: "assistant", responseId: "parent-response", timestamp: Date.now(), provider: "test", model: "test", usage, stopReason: "stop" };
  const summary = { id: "compact1", type: "compaction", timestamp: new Date().toISOString(), usage, summary: "PRIVATE SUMMARY" };
  const entries = [{ type: "message", message }, summary];
  const ctx = { sessionManager: { getSessionId: () => "p", getHeader: () => ({ id: "p" }), getSessionFile: () => parentFile, getEntries: () => entries }, ui: { setStatus() {} } };
  const observer = new Observer(dir); await observer.start(ctx);
  observer.event({ type: "session_compact", compactionEntry: summary });
  assert.equal(observer.store.ledger.summarize("p").requests, 2);
  const childMessage = { ...message, responseId: "child-response" };
  await writeFile(childFile, [JSON.stringify({ type: "session", id: "c", parentSession: parentFile }), JSON.stringify({ type: "message", message: childMessage })].join("\n") + "\n");
  observer.event({ type: "tool_execution_end", toolName: "second_opinion_agent", result: { details: { childSessionPath: childFile } } });
  await observer.stop();
  assert.equal(observer.store.ledger.summarize("p").requests, 3);
  assert.equal(observer.store.ledger.summarize("p").costUsd, 0.03);
  const resumed = new Observer(dir); await resumed.start(ctx);
  assert.equal(resumed.store.ledger.summarize("p").requests, 3);
  assert.equal(resumed.store.ledger.summarize("p").timedRequests, 0);
  await resumed.stop();
});
test("foreign child transcript is rejected and single-chunk TPS stays unknown", async () => {
  const dir = await mkdtemp(join(tmpdir(), "usage-observer-"));
  const childFile = join(dir, "foreign.jsonl");
  await writeFile(childFile, JSON.stringify({ type: "session", id: "foreign", parentSession: "/different/parent.jsonl" }) + "\n");
  const observer = new Observer(dir);
  const ctx = { sessionManager: { getSessionId: () => "p", getSessionFile: () => join(dir, "parent.jsonl") }, ui: { setStatus() {} } };
  await observer.start(ctx);
  await observer.importChild(childFile);
  assert.equal(observer.store.ledger.sessions.has("foreign"), false);
  const message = { role: "assistant", provider: "test", model: "test", responseId: "r", timestamp: Date.now(), usage, stopReason: "stop" };
  observer.event({ type: "message_start", message });
  observer.event({ type: "message_update", assistantMessageEvent: { type: "text_delta", delta: "only chunk" } });
  observer.event({ type: "message_end", message });
  assert.equal(observer.store.ledger.summarize("p").tps, undefined);
  await observer.stop();
});
